project:
  type: website
  output-dir: docs

website:
  title: "Communicating with Data by Melisa"
  navbar:
    collapse-below: sm
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Blog
        file: posts/index.qmd
    right:
      - icon: github
        href: https://github.com/Melisa-ops

format:
  html:
    theme:
      light: minty #sketchy
      dark: slate #darkly
    css: "styles.css"
