project:
  type: website

website:
  title: "Communicating with Data by Melisa"   # (1) sensible title
  navbar:
    collapse-below: sm
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Blog
        file: posts/index.qmd
    right:
      - icon: github                           # (2) link ke GitHub
        href: https://github.com/Melisa-ops

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: "styles.css"
