project:
  type: website
  output-dir: docs

website:
  title: "Communicating with Data by Melisa"
  navbar:
    collapse-below: sm
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      #- href: posts/index.qmd
       # text: Blog
    right:
      - icon: github
        href: https://github.com/Melisa-ops

format:
  html:
    theme:
      light: minty
      dark: slate
    css: "styles.css"
